# This is a basic workflow to help you get started with Actions

name: Prod

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Dev"]
    branches: [main]
    types:
      - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  vga-prod:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Create release document (Prod)
        shell: powershell
        run: .\CreateJob.ps1 -IsFinal
        
  production:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: production
    needs: vga-prod
    steps:
      - uses: actions/checkout@v2
      - name: Mark Production job
        shell: pwsh
        run: .\MarkEnvironment.ps1
      - name: Deploy to production
        run: echo Deployed to production!
